### ISSUE TITLE
SST train data size 6920

### ISSUE THREAD

**Issue by Opdoop** [thunlp/OpenAttack#146]
I'm confused with the data size.
GLUE/SST2 the train/dev/test split is 67,349/872/1,821 
Your "https://thunlp.oss-cn-qingdao.aliyuncs.com/TAADToolbox/dataset/sst.pkl" train/dev/test splits split is 6920/872/1821 
What's the difference? Did I miss something?

**Comment by Cypredar** [comment]
I'm sorry for the late reply. I will communicate with the student responsible for uploading the data set and reply as soon as possible.

**Comment by Fanchao-Qi** [comment]
@Opdoop Hi, thank you for your question.

According to our observation and statistics, the SST-2 dataset used in GLUE is different from the original version of SST-2 indeed. The original SST dataset comprises 11,855 sentences extracted from movie reviews [[Socher et al. 2013](https://www.aclweb.org/anthology/D13-1170.pdf)]. It annotates sentiments not only for each sentence but for the constituent phrases of each sentence as well, and there are 215,154 unique phrases in total.

We use the original SST-2 dataset that only comprises the **complete** sentences that are not labelled neutral, and its original split is 6920/872/1821. [[Socher et al. 2013](https://www.aclweb.org/anthology/D13-1170.pdf)]

As for the SST-2 in GLUE, we check its instances and find that many phrases (rather than complete sentences) are included, even the phrases that are constituents of other phrases/sentences. However, not all 215,154 unique phrases are in it. We are also curious about how this dataset is built and why, but find no clues in the GLUE paper or other sources.

However, considering the popularity of GLUE, we will include its SST-2 version in our toolkit as soon as possible.

**Comment by junyann** [comment]
I found a discussion on twitter: https://twitter.com/BastingsJasmijn/status/1236630315881431042.
There are still not enough details on how to get the GLUE/SST-2 dataset from the original SST-2 dataset but relevant researchers (including the first author of GLUE) provided some clues. I think these two datasets can just be considered as two different versions of SST-2 (with significantly different sizes).
