### ISSUE TITLE
Does OpenAttack2.0 support NER

### ISSUE THREAD

**Issue by helloworldhellokitty** [thunlp/OpenAttack#219]

**Comment by Fanchao-Qi** [comment]
Sorry that OpenAttack 2.0 doesn't support attacks against NER models, because we haven't found any studies on attacks on NER. In fact, adversarial attacks against NER are not well defined, e.g., is it OK to perturb the entity sequence? what is the aim of attacks (misclassify an entity or wrongly recognize a sequence)?
