### ISSUE TITLE
Tokenizers in pertained models do not have a lang tag

### ISSUE THREAD

**Issue by leix28** [thunlp/OpenAttack#227]
what I did:

```
import OpenAttack as oa
victim = oa.DataManager.loadVictim("ROBERTA.AG")
```

Then

- `victim.tokenizer.TAGS` is `{None}`
- `victim.tokenizer.__lang_tag` gets `AttributeError: 'TransformersTokenizer' object has no attribute '__lang_tag'`

I tried to fix it by `victim.tokenizer.__lang_tag = oa.tags.TAG_English`. But it does not resolve the issue. I still get the same errors.

**Comment by Hongcheng-Gao** [comment]
The '__lang_tag' is the private property of 'TransformersTokenizer'  so that you can't access.
Hence, we set the default TAGS "TAG_English" and then added the interface to modify the TAGS by "victim.tokenizer.TAGS=xxx".

**Comment by Hongcheng-Gao** [comment]
For question 1,  we fix it to that "if is `None` then `TransformersClassifier` will intelligently select the language based on other parameters."

For question 2, the '__lang_tag' is the private property of 'TransformersTokenizer' so that you couldn't access. We added the interface to modify the TAGS by "victim.tokenizer.TAGS=xxx".
