### ISSUE TITLE
I had A problem run demo.py

### ISSUE THREAD

**Issue by ouhongxu** [thunlp/OpenAttack#97]
I had a problem with the last sentence of the demo（“attack_eval.eval(dataset, visualize=True)”）, and I don't know why
![image](https://user-images.githubusercontent.com/60462613/89164242-6cd04800-d5a9-11ea-81cf-c699d933a723.png)

**Comment by zhougr18** [comment]
This problem is caused by nltk.data.load which perfomers differently when facing different paths on Windows. You can add the following piece of code right after "import OpenAttack" to solve the problem.

def nltk_loader(loader):
    return lambda x: loader('file:' + x)
for name in OpenAttack.DataManager.data_loader:
    if name in ["TProcess.NLTKSentTokenizer", "TProcess.NLTKPerceptronPosTagger"]:
        OpenAttack.DataManager.data_loader[name] = \
            nltk_loader(OpenAttack.DataManager.data_loader[name])

We will handle this trouble in the next version.

**Comment by ouhongxu** [comment]
When I put the following code at the beginning of Demo.py, I ran into a new problem (as shown in the screenshot).
```
def nltk_loader(loader):
    return lambda x: loader('file:' + x)
for name in OpenAttack.DataManager.data_loader:
    if name in ["TProcess.NLTKSentTokenizer", "TProcess.NLTKPerceptronPosTagger"]:
        OpenAttack.DataManager.data_loader[name] = \
            nltk_loader(OpenAttack.DataManager.data_loader[name])
```
![image](https://user-images.githubusercontent.com/60462613/89199014-8fca1e80-d5e0-11ea-9fa5-6955f1d8fe87.png)
